#ifndef NUMERICREPLIES
#define NUMERICREPLIES

enum Numeric
{
    RPL_WELCOME = 1,
    RPL_YOURHOST = 2,
    RPL_CREATED = 3,
    RPL_MYINFO = 4,
    RPL_ISUPPORT = 5,
    RPL_TOPIC = 332,
    RPL_NOTOPIC = 331,
    RPL_NAMREPLY = 353,
    RPL_ENDOFNAMES = 366,
    RPL_INVITING = 341,
    RPL_CHANNELMODEIS = 324,
    RPL_CREATIONTIME = 329,
    RPL_INVITELIST = 336,
    RPL_ENDOFINVITELIST = 337,

    ERR_NOSUCHNICK = 401,
    ERR_NOSUCHCHANNEL = 403,
    ERR_NICKNAMEINUSE = 433,
    ERR_NEEDMOREPARAMS = 461,
    ERR_CHANOPRIVSNEEDED = 482,
    ERR_UNKNOWNCOMMAND = 421,
    ERR_ALREADYREGISTERED = 462,
    ERR_PASSWDMISMATCH = 464,
    ERR_NONICKNAMEGIVEN = 431,
    ERR_ERRONEUSNICKNAME = 432,
    ERR_USERNOTINCHANNEL = 441,
    ERR_NOTONCHANNEL = 442,
    ERR_NOTREGISTERED = 451,
    ERR_INVITEONLYCHAN = 473,
    ERR_BADCHANNELKEY = 475,
    ERR_CHANNELISFULL = 471,
    ERR_USERONCHANNEL = 443,
    ERR_UNKNOWNMODE = 472,
    ERR_KEYSET = 467,
    ERR_INVALIDMODEPARAM = 696,
    ERR_NOORIGIN = 409,
    ERR_NORECIPIENT = 411,
    ERR_NOTEXTTOSEND = 412,
    ERR_TOOMANYTARGETS = 407,
    ERR_CANNOTSENDTOCHAN = 404,
    ERR_INVALIDCAPCMD = 410
};

#endif